services:
  dockcheck:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dockcheck
    image: dockcheck:latest
    volumes:
      - ./config.json:/dockcheck/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Etc/UTC
    restart: always
networks: {}
